### ISSUE TITLE
Latest release is broken

### ISSUE THREAD

**Issue by morr0ne** [hyprland-community/hyprland-rs#113]
Version 0.3.10 breaks because of pr #108, It changes monitor to a u64 which is incorrect since that value can actually be -1. It should instead be a i64. This should be reversed and the release yanked. Some of my project started breaking because of this issue.

**Comment by yavko** [comment]
Oh shit

**Comment by morr0ne** [comment]
> Oh shit

Can't say that's the response I was expecting, although it accurately depicts the situation

**Comment by yavko** [comment]
Okay I changed it, I'll make a new release and yank

**Comment by yavko** [comment]
Problem is I can't make a crates.io release cuz I'm on phone rn

**Comment by morr0ne** [comment]
Closing since it has been resolved
