### ISSUE TITLE
`Client::get_active()` doesn't work

### ISSUE THREAD

**Issue by c0h2r** [hyprland-community/hyprland-rs#124]
Calling the method with an active window present results in smth like that:

```
[src/main.rs:210] Client::get_active() = Err(
    SerdeError(
        Error("data did not match any variant of untagged enum Aux", line: 0, column: 0),
    ),
)
```

And when there's none, everything works fine:

```
[src/main.rs:210] Client::get_active() = Ok(
    None,
)
```

Attempts at debugging showed that the problem is with [trying to deserialize json into `ActiveWindow`](https://github.com/hyprland-community/hyprland-rs/blob/master/src/data/regular.rs#L262). Maybe it'd be easier to manually check if the result [edit: of the ipc call] is empty instead of doing that proxy struct thingy?

In case of inability to replicate: I'm on NixOS, and `hyprctl version` says

```
hyprctl version
Hyprland, built from branch  at commit v0.30.0  ().
Tag: ?

flags: (if any)
debug
```

Also, if I manually feed `serde` with an output of `hyprctl activewindow -j`, it is able to parse the output into structs provided by the crate.

[edit: Also^2: the `data` variable right before parsing looks fine when `print`ed from `rust-gdb`.]
[edit: just in case, [here's an asciinema recording](https://asciinema.org/a/VfksJaBUQpRsFDJQhlauQrSFl)]

**Comment by vars1ty** [comment]
@yavko ?

**Comment by H3rmt** [comment]
I checked against some recent commits and found that [this](https://github.com/hyprland-community/hyprland-rs/commit/0c35ba168a11be61820da3ac7f4b9e499d232b33) commit broke serializing the json into ActiveWindow

seems like i64 is the correct type for monitor-ids

Here is a history which commits are broken:
```

# Error: SerdeError(Error("data did not match any variant of untagged enum Aux", line: 0, column: 0))
#hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", rev = "0c35ba168a11be61820da3ac7f4b9e499d232b33" }

# working fine
#hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", rev = "597720809b1c92b25eb4eb71c04e673560ae673c" }

# Error: SerdeError(Error("data did not match any variant of untagged enum Aux", line: 0, column: 0))
#hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", rev = "4580068e32a13a29ef03730158e7e8b7b30c14f1" }

# working fine
#hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", rev = "fe7e4ee945ba905499b8216ced674f22447ce16a" }

# Error: SerdeError(Error("invalid value: integer `-1`, expected u64", line: 12, column: 17))
#hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", rev = "e58d6e2798e41ca0e42c3e9455d65ddd1eba5153" }

# working fine
#hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", rev = "aae818caaf35730ac6188a18a0157ee62bf636b8" }

# Error: SerdeError(Error("invalid value: integer `-1`, expected u64", line: 12, column: 17))
#hyprland = { git = "https://github.com/hyprland-community/hyprland-rs",rev = "12afa388e5326c2f9cf7b44009a545d3f37c3779"}

# working fine
#hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", rev = "bc61818e5a9a41b4bef174b37124325365008294" }
```

**Comment by yavko** [comment]
Omg how did I never get notified about this issue....

**Comment by yavko** [comment]
> I checked against some recent commits and found that [this](https://github.com/hyprland-community/hyprland-rs/commit/0c35ba168a11be61820da3ac7f4b9e499d232b33) commit broke serializing the json into ActiveWindow
> 
> seems like i64 is the correct type for monitor-ids
> 
> Here is a history which commits are broken:
> 
> ```
> 
> # Error: SerdeError(Error("data did not match any variant of untagged enum Aux", line: 0, column: 0))
> #hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", rev = "0c35ba168a11be61820da3ac7f4b9e499d232b33" }
> 
> # working fine
> #hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", rev = "597720809b1c92b25eb4eb71c04e673560ae673c" }
> 
> # Error: SerdeError(Error("data did not match any variant of untagged enum Aux", line: 0, column: 0))
> #hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", rev = "4580068e32a13a29ef03730158e7e8b7b30c14f1" }
> 
> # working fine
> #hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", rev = "fe7e4ee945ba905499b8216ced674f22447ce16a" }
> 
> # Error: SerdeError(Error("invalid value: integer `-1`, expected u64", line: 12, column: 17))
> #hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", rev = "e58d6e2798e41ca0e42c3e9455d65ddd1eba5153" }
> 
> # working fine
> #hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", rev = "aae818caaf35730ac6188a18a0157ee62bf636b8" }
> 
> # Error: SerdeError(Error("invalid value: integer `-1`, expected u64", line: 12, column: 17))
> #hyprland = { git = "https://github.com/hyprland-community/hyprland-rs",rev = "12afa388e5326c2f9cf7b44009a545d3f37c3779"}
> 
> # working fine
> #hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", rev = "bc61818e5a9a41b4bef174b37124325365008294" }
> ```

I can't decide on what type to use for that damn field. People keep submitting pull requests that "fix" it, but only fix it for them. Honestly, I can't even debug this as I'm temporarily not on linux. So I need someone else to figure this out for me

**Comment by H3rmt** [comment]
this is a known bug with serde (https://github.com/serde-rs/serde/issues/1682)

**Comment by H3rmt** [comment]
Hi @yavko, when is the next release scheduled?
I'm currently stuck on hyprland=0.3.11, but I would like to use focus_history_id. (https://github.com/hyprland-community/hyprland-rs/commit/00505b0c1510fa2c5f33fa11bac016b5621713e7) (https://github.com/H3rmt/WindowSwitcher/issues/5)

**Comment by yavko** [comment]
I'll create a new release when I get home

**Comment by yavko** [comment]
> Hi @yavko, when is the next release scheduled?
> I'm currently stuck on hyprland=0.3.11, but I would like to use focus_history_id. (https://github.com/hyprland-community/hyprland-rs/commit/00505b0c1510fa2c5f33fa11bac016b5621713e7) (https://github.com/H3rmt/WindowSwitcher/issues/5)

There was a release yesterday btw
