### ISSUE TITLE
License

### ISSUE THREAD

**Issue by donovanglover** [hyprland-community/hyprland-rs#132]
Was doing a [`cargo license`](https://github.com/onur/cargo-license) check and noticed the license of hyprland-rs.

As far as I'm aware, the GPL license would require all programs that use hyprland-rs to be GPL'd.

If this is intended, can a short notice be added to the README? Many [existing projects](https://github.com/hyprland-community/hyprland-rs/network/dependents) use more permissive licenses and some none at all. As far as I'm aware, it's possible to use a [GPL-compatible](https://opensource.stackexchange.com/a/12979) license but the work as a whole would be GPL'd.

**Comment by yavko** [comment]
> Was doing a [`cargo license`](https://github.com/onur/cargo-license) check and noticed the license of hyprland-rs.
> 
> As far as I'm aware, the GPL license would require all programs that use hyprland-rs to be GPL'd.
> 
> If this is intended, can a short notice be added to the README? Many [existing projects](https://github.com/hyprland-community/hyprland-rs/network/dependents) use more permissive licenses and some none at all. As far as I'm aware, it's possible to use a [GPL-compatible](https://opensource.stackexchange.com/a/12979) license but the work as a whole would be GPL'd.

Personally, I don't want our code to be used in proprietary code bases, thus the GPL gives some protection for that. Also, I can't really re-license as, I'd need to get the approval of all contributors, and there doesn't seem to be a purpose in adding a notice. Ofc I could be wrong on any of this.

**Comment by donovanglover** [comment]
I don't mind the GPL personally. Looks like the README already has a badge which is cool. Maybe the `LICENSE` file can be updated so GitHub shows GPL in the sidebar?

**Comment by yavko** [comment]
> I don't mind the GPL personally. Looks like the README already has a badge which is cool. Maybe the `LICENSE` file can be updated so GitHub shows GPL in the sidebar?

I wrote the license properly, I'm not gonna change it just cuz GitHub's license detection sucks. If there is a way to make it know it's GPL I will but I don't wanna change the license

**Comment by donovanglover** [comment]
Looks like GitHub only shows GPL if you include the GPL text in `LICENSE` and the copyright notice elsewhere.

I don't think this matters too much so feel free to close this issue

**Comment by yavko** [comment]
> Looks like GitHub only shows GPL if you include the GPL text in `LICENSE` and the copyright notice elsewhere.
> 
> I don't think this matters too much so feel free to close this issue

Thats weird then
