### ISSUE TITLE
WorkspaceType::Named values over 99 will turn into 10

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprland-community/hyprland-rs#14]
```rust
  event_listener.add_workspace_added_handler(move |workspace, state| {
          dbg!(&workspace);
  });
  ```
Yeah. weird.
It seems like it only reads the first two digits, since if I'm at workspace 161, it would output `16`

**Comment by yavko** [comment]
> ```rust
> event_listener.add_workspace_added_handler(move |workspace, state| {
>         dbg!(&workspace);
> });
> ```
> 
> Yeah. weird. It seems like it only reads the first two digits, since if I'm at workspace 161, it would output `16`

Hmm, makes sense, as thats how the regex works. I'll have to make it larger

**Comment by yavko** [comment]
You know what I need to rework the entire workspace parsing, atm it only really works with 0-99 workspaces, barely with special workspace, and workspaces above 99, and named ones dont work at all

**Comment by yavko** [comment]
Fixed in https://github.com/hyprland-community/hyprland-rs/commit/925a415487a8aa357db46a86eb784d655bc211fd
![image](https://user-images.githubusercontent.com/15178513/210295126-a02019a1-8761-47b0-a974-3fddaff6ad1c.png)
