### ISSUE TITLE
Able to return both int and float

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprland-community/hyprland-rs#17]
![image](https://user-images.githubusercontent.com/68589851/211204935-f30bcb13-d082-4299-8301-6508b7081c29.png)
Currently Keyword::get_async only returns the Int, which is useless

**Comment by yavko** [comment]
> ![image](https://user-images.githubusercontent.com/68589851/211204935-f30bcb13-d082-4299-8301-6508b7081c29.png) Currently Keyword::get_async only returns the Int, which is useless

Hmm, I thought I had fixed that

**Comment by yavko** [comment]
It should be fixed, I'll fix it properly later

**Comment by yavko** [comment]
Properly fixed in https://github.com/hyprland-community/hyprland-rs/commit/ad58a55f6cb0213586f2c242b8f607c62622c5fa
