### ISSUE TITLE
Error: SerdeError(Error("missing field `int`", line: 1, column: 71))

### ISSUE THREAD

**Issue by donovanglover** [hyprland-community/hyprland-rs#184]
Getting this error in hyprdim 2.2.3 after updating Hyprland to 0.36.0.

Did a quick glance through the [changelog](https://github.com/hyprwm/Hyprland/releases/tag/v0.36.0) however I didn't see anything obvious that would cause it to break.

P.S. Is it possible to make these errors work with `RUST_BACKTRACE`?

**Comment by yavko** [comment]
> Getting this error in hyprdim 2.2.3 after updating Hyprland to 0.36.0.
> 
> Did a quick glance through the [changelog](https://github.com/hyprwm/Hyprland/releases/tag/v0.36.0) however I didn't see anything obvious that would cause it to break.
> 
> P.S. Is it possible to make these errors work with `RUST_BACKTRACE`?

what hyprland-rs version does it use

**Comment by yavko** [comment]
also plz provide more debug info, the actual json would be cool, rust backtrace also good

**Comment by yavko** [comment]
also for the better error system I mentioned, I know there are better ones, but afaik anyhow has a simple backrtrace for errors with the `backtrace` feature

**Comment by yavko** [comment]
Looking at the hyprland-rs and hyprland source code, I can't find anything with an `int` field
https://github.com/hyprwm/Hyprland/blob/main/src/debug/HyprCtl.cpp
https://github.com/hyprland-community/hyprland-rs/blob/master/src/data/regular.rs

**Comment by donovanglover** [comment]
Tested with hyprland-rs 0.3.9 and 0.3.13. Will investigate more later.

One weird thing I noticed is that one of my shell scripts broke since `hyprctl getoption general:gaps_in` returns `invalid type (internal error)`

**Comment by donovanglover** [comment]
Related? https://github.com/hyprwm/Hyprland/issues/5025

**Comment by yavko** [comment]
It seems like the switch to hyprlang broke keywords, i see where the issue is now, probably getoption doesn't return a object anymore or something like that

**Comment by donovanglover** [comment]
Built hyprland with the latest commit on main to fix https://github.com/hyprwm/Hyprland/issues/4974 and hyprlang @ 0.5.0 and it looks like `gaps_in` and some other stuff use a `custom` field now

**Comment by JarKz** [comment]
Seems, there is the major changes in last Hyprland version with `getoption` command. I tested in my machine and it returns different results since pre-last Hyprland version. Give me some time and I'll make PR with fix.

**Comment by JarKz** [comment]
Fixed, y'all can use the git version.
