### ISSUE TITLE
Release 0.3 alpha

### ISSUE THREAD

**Issue by cyrinux** [hyprland-community/hyprland-rs#20]
Hey, 
Can you please cut a release ?
I would like to release my toy using the lib with some master feature ;)
Thanks!

**Comment by yavko** [comment]
I'm working on getting out a alpha release so crates on crates.io can use, but for now you can use `hyprland = { git = "https://github.com/hyprland-community/hyprland-rs.git" }`

**Comment by yavko** [comment]
I've released an alpha! https://github.com/hyprland-community/hyprland-rs/releases/tag/0.3.0-alpha.0
