### ISSUE TITLE
broken pipe panic /.../hyprland-0.3.13/src/data/regular.rs:17:19

### ISSUE THREAD

**Issue by thrombe** [hyprland-community/hyprland-rs#204]
hyprland-rs sometimes panics when device wakes up from sleep.
the panic is [here](https://github.com/hyprland-community/hyprland-rs/blob/7a60845c9bfaf264e4dd9f5d7977f4a1f15599c8/src/data/regular.rs#L17).
I read the code and don't really see a reason for the panic when it could have been an error.
Am i missing something?
Should I make a simple PR for it?

**Comment by thrombe** [comment]
this is the entire error.
```
A error occured while parsing the output from the hypr socket: IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
```

**Comment by yavko** [comment]
> this is the entire error.
> 
> ```
> thread 'main' panicked at /build/cargo-vendor-dir/hyprland-0.3.13/src/data/regular.rs:17:19:
> A error occured while parsing the output from the hypr socket: IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
> ```

try the sync version

**Comment by thrombe** [comment]
I was trying to reproduce this - but it doesn't always happen. so i can't test it with the sync version quickly either.
i could try it with sync - but [the sync version](https://github.com/hyprland-community/hyprland-rs/blob/7a60845c9bfaf264e4dd9f5d7977f4a1f15599c8/src/data/regular.rs#L31) has a similar panic.

is there a specific reason why you suggest this?
