### ISSUE TITLE
[ Bug ] Can't not get any keyword

### ISSUE THREAD

**Issue by robertlc04** [hyprland-community/hyprland-rs#217]
Im traing to make a unix socket server and in the moment i have to get the keyword of hypr using the library I get just an error but i test in the terminal with hyprctl command and works perfect

hyprctl:
```bash
hyprctl getoption general:gaps_in
```
output ``
custom type: 5 5 5 5
set: true
``

My function:
```rust
fn change() -> Result<()>  {
    let border_size = match Keyword::get("general:gaps_in") {
        Ok(x) => println!("{x:?}"),
        Err(e) => println!("{e:?}"),
    };
    Ok(())
}
```

Imports: 
```rust
use std::os::unix::net::{UnixListener, UnixStream};
use std::io::prelude::*;
use std::{env, thread};

use hyprland::keyword::{Keyword, OptionValue};
use hyprland::Result;```

Output Err:``SerdeError(Error("missing field `int`", line: 1, column: 64))``

**Comment by yavko** [comment]
This issue is fixed on the master branch, I'll try to get a release out whenever I have free time, but I just can't right now because of school

**Comment by yavko** [comment]
Also hyprland-rs manages it's own sockets, no need to make one

**Comment by yavko** [comment]
exists in the new alpha
