### ISSUE TITLE
Support for workspace specific moving

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprland-community/hyprland-rs#27]
![image](https://user-images.githubusercontent.com/68589851/215048750-7410150e-deed-4e4b-9caa-f59bebb5e569.png)

**Comment by yavko** [comment]
I'll add this first chance tomorrow.

**Comment by yavko** [comment]
fixed in https://github.com/hyprland-community/hyprland-rs/commit/bfd974b667babe245823d3d47457c553a0f10acb
