### ISSUE TITLE
Create issue forms

### ISSUE THREAD

**Issue by yavko** [hyprland-community/hyprland-rs#28]
Pretty self-explanatory, this will be done to make it easier, and standardize issues for like adding dispatchers as an example. I want this to be integrated with `0.3.1` to make it easier to report missing dispatchers.

**Comment by JustSimplyKyle** [comment]
Additionally, I think there should be a always open issue for missing IPC events

**Comment by yavko** [comment]
I was gonna do this but kept forgetting too lol, ill just copy the ones from hyprland-community/submissions

**Comment by yavko** [comment]
> Additionally, I think there should be a always open issue for missing IPC events

good idea

**Comment by yavko** [comment]
added in https://github.com/hyprland-community/hyprland-rs/commit/7e9f40daa73dddb40d90097e80eec9d021fda730
