### ISSUE TITLE
Add support for resizewindowpixel and movewindowpixel

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprland-community/hyprland-rs#3]
If it's possible, I would also like to use address instead of title, but that's on you

**Comment by yavko** [comment]
> If it's possible, I would also like to use address instead of title, but that's on you

I'll see if I have time to do it, also can you explain like what it is exactly?

**Comment by KyleUltimate** [comment]
basically, it allows resize without focusing.
![image](https://user-images.githubusercontent.com/68589851/186069950-596b4722-2155-4219-868a-593176a391b6.png)

**Comment by yavko** [comment]
> basically, it allows resize without focusing. ![image](https://user-images.githubusercontent.com/68589851/186069950-596b4722-2155-4219-868a-593176a391b6.png)

Ah, I mean by address, but I see what you mean

**Comment by yavko** [comment]
Fixed in master https://github.com/hyprland-community/hyprland-rs/commit/96654efc3eaf115ea78eb33fc2889b7d6315c626
