### ISSUE TITLE
ToggleSpecialWorkspace dispatcher does not take any arguments

### ISSUE THREAD

**Issue by mhats** [hyprland-community/hyprland-rs#31]
First of all, thanks a lot for this project!

The hyprland dispatcher togglespecialworkspace takes an optional argument for specifying the name of the special workspace. The ToggleSpecialWorkspace in dispatch.rs does not seem to have any way of specifying the workspace name.

Please let me now if I am missing something.

**Comment by yavko** [comment]
This is indeed the case, how did I not see this lol

**Comment by yavko** [comment]
Fixed in https://github.com/hyprland-community/hyprland-rs/commit/530839b47f844ae1022f0aa60d99c871aa05507b
