### ISSUE TITLE
`0.3.1` release

### ISSUE THREAD

**Issue by yavko** [hyprland-community/hyprland-rs#39]
It's been more than a month, so it's time for a new release, if anyone wants small changes please request here, so they can be seen in next stable release. Thanks!
To-do:
- [x] Add all layout dispatchers #35
- [x] Add minimize event
- [x] Add group dispatchers

**Comment by yavko** [comment]
#35 was finished, almost there!

**Comment by yavko** [comment]
It's been a month since I made this issue, everything is done, why didn't I release? I don't know, anyway, `0.3.1` coming later today!! :)

**Comment by cyrinux** [comment]
https://github.com/cyrinux/hyprland-autoname-workspaces/issues/9 is waiting for you ❤️

**Comment by yavko** [comment]
> [cyrinux/hyprland-autoname-workspaces#9](https://github.com/cyrinux/hyprland-autoname-workspaces/issues/9) is waiting for you heart

I'm having issues with publishing the proc-macro crate, so yeah, actually probably today. Sorry for the miss info lol

**Comment by yavko** [comment]
DONE!!
