### ISSUE TITLE
Add support for various IPC events

### ISSUE THREAD

**Issue by JustSimplyKyle** [hyprland-community/hyprland-rs#4]
https://github.com/hyprwm/Hyprland/pull/557
I think this is what caused the current IPC panic when a new window is created

**Comment by yavko** [comment]
They have been added to master, at least afaik, anyways
For those wanting to test out `0.3.0`, you can do so by
```toml
hyprland = { git = "https://github.com/hyprland-community/hyprland-rs.git" }
```
