### ISSUE TITLE
Serialization issue with latest hyprland

### ISSUE THREAD

**Issue by patrikha** [hyprland-community/hyprland-rs#51]
Hi,

Using hyprland-workspaces and trying to get active workspace I get a panic!

Sample command:
```
hyprland-workspaces DP-1
[{"active":false,"class":"workspace-button w1","id":1,"name":"1"}]
thread 'main' panicked at 'Error parsing data whith serde: expected value at line 1 column 1', /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/hyprland-0.3.3/src/event_listener/mutable.rs:53:31
```

Could the data structure have changed/optionals to cause the serde parser to panic?
```
        let data = call_hyprctl_data_cmd(DataCommands::ActiveWorkspace);
        let deserialized: Workspace = serde_json::from_str(&data)?;
```

**Comment by yavko** [comment]
Works as intended, update Hyprland, this crate always is built on the changes in master. Also this was changed in 0.24 iirc

**Comment by yavko** [comment]
Also idk what hyprland-workspaces is

**Comment by patrikha** [comment]
Ok I will check with the [hyprland-workspaces](https://github.com/FieldofClay/hyprland-workspaces) maintainer.

You can close the issue.

**Comment by patrikha** [comment]
Just one more comment, rolling back to 0.3.2 of hyprland-rs works so there might still be something to look at

cheers
