### ISSUE TITLE
[Event]: urgent

### ISSUE THREAD

**Issue by JakeStanger** [hyprland-community/hyprland-rs#52]
### What is the name of the event

urgent

---

Full log from `ironbar`:

```
A unknown event was passed into Hyprland-rs
PLEASE MAKE AN ISSUE!!
The event was: urgent>>55fc37dad5d0
```

I believe this got triggered after clicking a link in discord, which was opened in Firefox.

**Comment by yavko** [comment]
Yeah, this is already added, just update hyprland-rs, also if you don't want these logs anymore, enable the `silent` feature flag (`0.3.2` and later)
> Also I update hyprland-rs in https://github.com/JakeStanger/ironbar/pull/147 (from `0.3.2` in one commit and to `0.3.3` in another)

**Comment by JakeStanger** [comment]
Ah cool okay, I should have checked that before opening. Cheers
