### ISSUE TITLE
[Event]: windowtitle>>555ef349f500

### ISSUE THREAD

**Issue by dtomvan** [hyprland-community/hyprland-rs#70]
### What is the name of the event

windowtitle>>555ef349f500

**Comment by yavko** [comment]
Use latest version

**Comment by yavko** [comment]
Should've been added in https://github.com/hyprland-community/hyprland-rs/releases/tag/0.3.4

**Comment by dtomvan** [comment]
Hmm, sorry for bothering you, while using ironbar I got a message to submit an issue on your project so that's what I did. Have a nice day!

**Comment by yavko** [comment]
> Hmm, sorry for bothering you, while using ironbar I got a message to submit an issue on your project so that's what I did. Have a nice day!

Ah, makes sense! I currently have a PR in ironbar that should update it once merged :)
