### ISSUE TITLE
Can't dispatch ToggleFloating event on newly open window

### ISSUE THREAD

**Issue by Gustash** [hyprland-community/hyprland-rs#82]
Trying to dispatch a `ToggleFloating` event on a `window_open_handler` event listener does not float the newly open window.

I'm trying to use the `data.window_address` to make sure only the newly open window gets floated, but this does nothing to the window. If I call `DispatchType::ToggleFloating` with `None` instead, the new window gets floated, but I want more predictable behavior when doing so.

Below is the code I'm using, which can be used to replicate this issue:

```rust
use hyprland::{
    dispatch::{Dispatch, DispatchType, WindowIdentifier},
    event_listener::{EventListener, WindowOpenEvent},
    Result,
};

#[tokio::main]
async fn main() -> Result<()> {
    let mut listener = EventListener::new();

    listener.add_window_open_handler(|data| float_window(&data));
    listener.start_listener_async().await
}

fn float_window(data: &WindowOpenEvent) {
    let window_address = data.window_address.clone();
    println!("Window Address: {}", window_address);
    if let Err(err) = Dispatch::call(DispatchType::ToggleFloating(Some(
        WindowIdentifier::Address(window_address),
    ))) {
        println!("Error: {:#?}", err);
    }
}
```

**Comment by yavko** [comment]
Can you check that the address provided by the event is the correct one?

**Comment by Gustash** [comment]
It is, I get `Window 561089bad4d0 -> hyprctl clients /:` from `hyprctl clients`, and the first `println!` prints out `Window Address: 561089bad4d0`

**Comment by Gustash** [comment]
Found the problem. It seems like the address needs to be formatted as `0xDEADBEEF` instead of just `DEADBEEF`.

**Comment by yavko** [comment]
> Found the problem. It seems like the address needs to be formatted as `0xDEADBEEF` instead of just `DEADBEEF`.

Hmm, I'm not sure if it should be changed or not, since 0x is a syntax thing, and the hex is that actual data

**Comment by yavko** [comment]
> > Found the problem. It seems like the address needs to be formatted as `0xDEADBEEF` instead of just `DEADBEEF`.
> 
> Hmm, I'm not sure if it should be changed or not, since 0x is a syntax thing, and the hex is the actual data

I believe the solution should be to add a new function to convert it to a formatted string

**Comment by Gustash** [comment]
I tested the fix with this codebase and it seems to work, but maybe it needs a bit more testing to check if it doesn't affect anything else.

**Comment by yavko** [comment]
> I tested the fix with this codebase and it seems to work, but maybe it needs a bit more testing to check if it doesn't affect anything else.

Seems the specific issue doesn't exist in the codebase, but the solution I proposed to prevent this in the future has been made into an issue
